### ISSUE TITLE
Marry 

### ISSUE THREAD

**Issue by noesd** [NikoBotDev/Niko#1]
Marry bug http://www.noelshack.com/2018-23-2-1528150141-af5221cc-f64c-4d10-aebf-4f8ba3e9e5ff.png

**Comment by NikoBotDev** [comment]
The URL is not working, sorry for the lateness 😶

**Comment by noesd** [comment]
It works for me
I can send it in the Discord if you want

**Comment by NikoBotDev** [comment]
It was just a bug in mobile, i guess it's fixed now in ad0d3b4, i do not will up this commit yet because some previous commit in this file has breaking changes.
